name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

  validate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
      - name: Lint
        run: npm run lint

  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
      - name: Lint
        run: npm test

  release:

    runs-on: ubuntu-latest

    steps:
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: maxencelanda
        minimum-approvals: 1
        issue-title: ""
        issue-body: ""
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''
    - uses: release-drafter/release-drafter@v6
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}