name: Deploy Pipeline

on:
  workflow_dispatch:  # Déclenchement manuel nécessaire

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # Utilise le nom du tag poussé
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changelog
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}